In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("csvs/bodyPerformance.csv")
df

age gender  height_cm  weight_kg  body fat_%  diastolic  systolic  \
0      27.0      M      172.3      75.24        21.3       80.0     130.0   
1      25.0      M      165.0      55.80        15.7       77.0     126.0   
2      31.0      M      179.6      78.00        20.1       92.0     152.0   
3      32.0      M      174.5      71.10        18.4       76.0     147.0   
4      28.0      M      173.8      67.70        17.1       70.0     127.0   
...     ...    ...        ...        ...         ...        ...       ...   
13388  25.0      M      172.1      71.80        16.2       74.0     141.0   
13389  21.0      M      179.7      63.90        12.1       74.0     128.0   
13390  39.0      M      177.2      80.50        20.1       78.0     132.0   
13391  64.0      F      146.1      57.70        40.4       68.0     121.0   
13392  34.0      M      164.0      66.10        19.5       82.0     150.0   

       gripForce  sit and bend forward_cm  sit-ups counts  broad jump_cm class  
0           54.9                     18.4            60.0          217.0     C  
1           36.4                     16.3            53.0          229.0     A  
2           44.8                     12.0            49.0          181.0     C  
3           41.4                     15.2            53.0          219.0     B  
4           43.5                     27.1            45.0          217.0     B  
...          ...                      ...             ...            ...   ...  
13388       35.8                     17.4            47.0          198.0     C  
13389       33.0                      1.1            48.0          167.0     D  
13390       63.5                     16.4            45.0          229.0     A  
13391       19.3                      9.2             0.0           75.0     D  
13392       35.9                      7.1            51.0          180.0     C  

[13393 rows x 12 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13393 entries, 0 to 13392
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   age                      13393 non-null  float64
 1   gender                   13393 non-null  object 
 2   height_cm                13393 non-null  float64
 3   weight_kg                13393 non-null  float64
 4   body fat_%               13393 non-null  float64
 5   diastolic                13393 non-null  float64
 6   systolic                 13393 non-null  float64
 7   gripForce                13393 non-null  float64
 8   sit and bend forward_cm  13393 non-null  float64
 9   sit-ups counts           13393 non-null  float64
 10  broad jump_cm            13393 non-null  float64
 11  class                    13393 non-null  object 
dtypes: float64(10), object(2)
memory usage: 1.2+ MB


### The work will be split in 2: the sklearn models, and the scartch implemention

In [4]:
df["gender"].replace({"M":0, "F":1}, inplace=True)
df["class"].replace({'A':1, 'B':2, 'C':3, 'D': 4}, inplace=True)

"""
Replacing the values that aren't integers or floats
 
masculine - 0
feminine - 1

A - 1;  B - 2;
C - 3;  D - 4;
"""
df

C:\Users\chris\AppData\Local\Temp\ipykernel_4692\775975626.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["gender"].replace({"M":0, "F":1}, inplace=True)
C:\Users\chris\AppData\Local\Temp\ipykernel_4692\775975626.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["gender"].replace({"M":0

age  gender  height_cm  weight_kg  body fat_%  diastolic  systolic  \
0      27.0       0      172.3      75.24        21.3       80.0     130.0   
1      25.0       0      165.0      55.80        15.7       77.0     126.0   
2      31.0       0      179.6      78.00        20.1       92.0     152.0   
3      32.0       0      174.5      71.10        18.4       76.0     147.0   
4      28.0       0      173.8      67.70        17.1       70.0     127.0   
...     ...     ...        ...        ...         ...        ...       ...   
13388  25.0       0      172.1      71.80        16.2       74.0     141.0   
13389  21.0       0      179.7      63.90        12.1       74.0     128.0   
13390  39.0       0      177.2      80.50        20.1       78.0     132.0   
13391  64.0       1      146.1      57.70        40.4       68.0     121.0   
13392  34.0       0      164.0      66.10        19.5       82.0     150.0   

       gripForce  sit and bend forward_cm  sit-ups counts  broad jump_cm  \
0           54.9                     18.4            60.0          217.0   
1           36.4                     16.3            53.0          229.0   
2           44.8                     12.0            49.0          181.0   
3           41.4                     15.2            53.0          219.0   
4           43.5                     27.1            45.0          217.0   
...          ...                      ...             ...            ...   
13388       35.8                     17.4            47.0          198.0   
13389       33.0                      1.1            48.0          167.0   
13390       63.5                     16.4            45.0          229.0   
13391       19.3                      9.2             0.0           75.0   
13392       35.9                      7.1            51.0          180.0   

       class  
0          3  
1          1  
2          3  
3          2  
4          2  
...      ...  
13388      3  
13389      4  
13390      1  
13391      4  
13392      3  

[13393 rows x 12 columns]

In [5]:
df.corr()["class"]

age                        0.065612
gender                    -0.075605
height_cm                  0.037753
weight_kg                  0.214129
body fat_%                 0.341956
diastolic                  0.066761
systolic                   0.035484
gripForce                 -0.136088
sit and bend forward_cm   -0.588123
sit-ups counts            -0.452832
broad jump_cm             -0.262154
class                      1.000000
Name: class, dtype: float64

# Correlation Notes
The biggest correlation with the class is the column "sit and bend forward", presumably because healthy people can reach their toesl, and are more elastic.

The second biggest correlation value is "sit up counts", because being able to do sit ups tells about your ability to move in different ways.

In [6]:
df_corr=df[["body fat_%", "sit and bend forward_cm", "sit-ups counts", "class"]]
df_corr[df_corr.columns[:-1]]


body fat_%  sit and bend forward_cm  sit-ups counts
0            21.3                     18.4            60.0
1            15.7                     16.3            53.0
2            20.1                     12.0            49.0
3            18.4                     15.2            53.0
4            17.1                     27.1            45.0
...           ...                      ...             ...
13388        16.2                     17.4            47.0
13389        12.1                      1.1            48.0
13390        20.1                     16.4            45.0
13391        40.4                      9.2             0.0
13392        19.5                      7.1            51.0

[13393 rows x 3 columns]

## Raw Sklearn

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, accuracy_score
from sklearn.linear_model import LogisticRegression

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=["class"]), df["class"], test_size=0.3, random_state=98765)
#splitting data

In [32]:
log_sklearn = LogisticRegression(max_iter=10000)  #training sklearn model on raw data
log_sklearn.fit(X_train, y_train)
y_pred=log_sklearn.predict(X_test)
y_pred

c:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([3, 1, 3, ..., 1, 4, 3], dtype=int64)

In [10]:
print(f"Accuracy Score Raw: {accuracy_score(y_test, y_pred)}")

Accuracy Score Raw: 0.6187157789945247


## Correlated Sklearn

In [11]:
X_train_corr, X_test_corr, y_train_corr, y_test_corr = train_test_split(df_corr[df_corr.columns[:-1]], df_corr["class"], test_size=0.3, random_state=56)
#splitting data

In [12]:
log_sklearn_corr = LogisticRegression(max_iter=10000)  #training sklearn model on correlated data
log_sklearn_corr.fit(X_train_corr, y_train_corr)
y_pred_corr=log_sklearn_corr.predict(X_test_corr)

In [13]:
print(f"Accuracy Score Corr: {accuracy_score(y_test_corr, y_pred_corr)}")

Accuracy Score Corr: 0.5547536087605774


# Obsesrvations and conclusions
The accuracy score is between 50 and 60 %, which is not a bad thing. 
The accuracy for the correlated data was smaller because we had less paramiters to work with, and the correlation was not that big.
More parameteres would help with the mitigation of the error.


### Accuracy Scores:
Sklearn Raw : 0.61

Skealrn Corr : 0.54

## Scratch Raw

In [37]:
import numpy as np

class LogisticRegressionS:
    def __init__(self, learning_rate: float = 0.001, max_iter: int = 10000) -> None:
        """
        The constructor of the Logistic Regression model.
        :param learning_rate: float, default=0.05
        :param max_iter: int, default=100000
        """
        # Setting up the hyperparameters.
        self.__learning_rate = learning_rate
        self.__max_iter = max_iter

    def sigmoid(self, y: np.array) -> np.array:
        """The sigmoid function."""
        return 1 / (1 + np.exp(-y))

    def fit(self, X: np.array, y: np.array):
        """Fit the model."""
        # Ensure X is 2-dimensional
        X = X if X.ndim == 2 else X.reshape(-1, 1)
        self.coef_ = np.zeros(X.shape[1] + 1)

        # Add the intercept column
        X = np.hstack((X, np.ones((len(X), 1))))

        # Weights updating process
        for i in range(self.__max_iter):
            # Prediction
            pred = self.sigmoid(np.dot(X, self.coef_))

            # Compute the gradient
            gradient = np.dot(X.T, (pred - y)) / y.size

            # Update the weights
            self.coef_ -= gradient * self.__learning_rate

        return self

    def predict_proba(self, X: np.array) -> np.array:
        """Return class probabilities."""
        # Ensure X is 2-dimensional
        X = X if X.ndim == 2 else X.reshape(-1, 1)
        X = np.hstack((X, np.ones((len(X), 1))))

        # Compute probabilities
        prob = self.sigmoid(np.dot(X, self.coef_))
        return np.hstack(((1 - prob).reshape(-1, 1), prob.reshape(-1, 1)))

    def predict(self, X: np.array) -> np.array:
        """Return predictions."""
        # Ensure X is 2-dimensional
        X = X if X.ndim == 2 else X.reshape(-1, 1)
        X = np.hstack((X, np.ones((len(X), 1))))

        return (self.sigmoid(np.dot(X, self.coef_)) > 0.5).astype(int)

In [38]:
log_smlh=LogisticRegressionS()
log_smlh.fit(X_train, y_train)

In [42]:
y_pred_smlh=log_smlh.predict(X_test)
y_pred_smlh

array([1, 1, 1, ..., 1, 1, 1])

In [28]:
print(f"Accuracy Score Raw: {accuracy_score(y_test, y_pred_smlh)}")

Accuracy Score Raw: 0.2384270781483325


In [29]:
log_smlh_corr=LogisticRegressionS()
log_smlh_corr.fit(X_train_corr, y_train_corr)

In [30]:
y_pred_smlh_corr=log_smlh_corr.predict(X_test_corr)
y_pred_smlh_corr

array([1, 1, 1, ..., 1, 1, 1])

In [31]:
print(f"Accuracy Score Corralated: {accuracy_score(y_test_corr, y_pred_smlh_corr)}")

Accuracy Score Corralated: 0.2424091587854654


# Observations and Conclusions for Scratch Version

The accuracy is much lower, the corralated version being even slightly more accurate.

Edit: Model only predicts the outcome 1. Don't know why.
